language: cpp

compiler:
  - gcc
  - clang

before_install:
 - lsb_release -a 
 - sudo apt-get update
 - sudo apt-get upgrade 

install:
 - sudo apt-get install cmake
 - sudo apt-get install make
 - sudo apt-get install libboost-all-dev
 - sudo apt-get install libhtmlcxx-dev
 - sudo apt-get install libcurl4-dev

before_script:
 - cd coil
 
script:
 - make --jobs
 