language: cpp

compiler:
  - gcc
  - clang

before_install:
 - lsb_release --all
 - sudo apt-get --yes --quiet install python-software-properties
 - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository --yes ppa:boost-latest/ppa
 - sudo add-apt-repository --yes 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
 - sudo apt-get --yes --quiet update
# - sudo apt-get --yes --quiet dist-upgrade

install:
 - sudo apt-get --yes --quiet install
   build-essential
   wget
   cmake
   gcc-4.8
   g++-4.8
   llvm-3.5
   clang-3.5
   libstdc++-4.8-dev
   libboost1.55-all-dev
   libhtmlcxx-dev
   libcurl4-*-dev
 - if test "$CC" == "gcc"; then
     sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6 &&
     sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8 &&
     sudo update-alternatives --auto gcc &&
     gcc --version;
   fi

before_script:
 - src_dir=$(pwd)
 - build_dir=$(mktemp --directory) 
# boost
# - boost_dir="$build_dir/boost"
# - mkdir --parents "$boost_dir"
# - url=http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.gz/download
# - wget -qO- "$url" | tar xz --strip-component=1 -C "$boost_dir" &&
#   cd "$boost_dir" &&
#   ./bootstrap.sh &&
#   ./b2 -j4 toolset=$CC
# glog
 - glog_dir="$build_dir/glog"
 - mkdir --parents "$glog_dir"
 - url="https://github.com/google/glog/archive/v0.3.4.tar.gz"
 - wget -qO- "$url" | tar xz --strip-component=1 -C "$glog_dir"
 - cd "$glog_dir"
 - ./configure
 - make -j4
 - sudo make install

script:
 - cmake -H$src_dir -B$build_dir && cmake --build $build_dir
 
after_success:
 - $build_dir/coil/tests
 - $build_dir/triangle/triangle
 - cd $build_dir/coil/ && ctest
